networks:
  adv-net:
    external: true
volumes:
  adv-ecommerce-db-vol:
  keycloak-e1-vol:
services:
  adv-ecommerce-api:
    image: adv-ecommerce-api:latest
    build:
      context: . #Dockerfile
    container_name: adv-ecommerce-api
    ports:
      - "8888:8888"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://adv-ecommerce-db:5432/db_ecommerce
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http:/localhost:9988/realms/ecommerce
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak-e1:8080/realms/ecommerce/protocol/openid-connect/certs
    networks:
      - adv-net
  adv-ecommerce-db:
    image: postgres:18.4
    container_name: adv-ecommerce-db
    ports:
      - "9999:5432"
    environment:
      POSTGRES_PASSWORD: 9903
      POSTGRES_USER: rotana
    volumes:
      - "./init_scripts:/docker-entrypoint-initdb.d"
      - "adv-ecommerce-db-vol:/var/lib/postgresql/18/docker"
    networks:
      - adv-net
  keycloak-e1:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: keycloak-e1
    environment:
      # Database
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://adv-ecommerce-db:5432/db_keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      # Admin
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      # Hostname v2 (Keycloak 26)
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT}
      KC_HOSTNAME_URL: ${KC_HOSTNAME_URL}
      KC_HOSTNAME_ADMIN_URL: ${KC_HOSTNAME_URL}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge

      # Other settings
      KC_PROXY_HEADERS: xforwarded
      KC_CACHE: ispn
      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      JAVA_OPTS_APPEND: "-Xms512m -Xmx2048m"
    command: start               # use in production mode
    #command: start-dev                        # use in development mode
    ports:
      - "127.0.0.1:9988:8080"
    volumes:
      - keycloak-e1-vol:/opt/keycloak/data
      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/conf:/opt/keycloak/conf
    networks:
      - adv-net
    depends_on:
      - adv-ecommerce-db
    restart: unless-stopped