file-upload:
  server-path: ${user.home}/Pictures/file-upload/
  client-path: "/file"
  base-uri: http://localhost:${server.port}${file-upload.client-path}
server:
  port: 8888
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/oauth2
  jpa:
    hibernate:
      ddl-auto: update # create, drop, alter, truncate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e1_ecommerce
    username: postgres
    password: 9903
  application:
    name: advanced-ecommerce

keycloak:
  clien-secret: clyBHwqR407iaOLWde0LaEgKoWDHcupW
  server-url: http://localhost:8080
  client-id: e1-springboot-client
  realm: oauth2