file-upload:
  server-path: ${user.home}/Pictures/file-upload/
  client-path: "/file"
  base-uri: http://localhost:${server.port}${file-upload.client-path}
server:
  port: 8888
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9988/realms/ecommerce
          jwk-set-uri: http://localhost:9988/realms/ecommerce/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update # create, drop, alter, truncate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9999/db_ecommerce
    username: rotana
    password: 9903
  application:
    name: advanced-ecommerce

keycloak:
  clien-secret: l8u35IMHs9ouxPdsuwDiEDiYjKaqu0ItB4zIE9h6pevM1TSjIjHax8NsMFhlvHxuRezPJMDpV0rufjZiadAPpe
  server-url: http://localhost:9988
  client-id: e1-springboot-client
  realm: ecommerce

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE